# Generated by Django 4.0.7 on 2022-10-04 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Notification title', max_length=120)),
                ('content', models.TextField(default='Notification content')),
                ('object_type', models.CharField(blank=True, max_length=120, null=True)),
                ('object_id', models.CharField(blank=True, max_length=120, null=True)),
                ('object_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('log', 'Log'), ('error', 'Error'), ('direct', 'Direct'), ('upload', 'Upload'), ('mail', 'Mail'), ('call', 'Call'), ('event', 'Event'), ('state-change', 'State change')], default='log', help_text='Notification type', max_length=15)),
                ('from_user_id', models.CharField(blank=True, max_length=120, null=True)),
                ('attach', models.FileField(blank=True, null=True, upload_to='files/notifications')),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
