# Generated by Django 4.0.7 on 2022-09-13 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/products')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('contact', models.CharField(blank=True, max_length=240, null=True)),
                ('documentation', models.FileField(blank=True, null=True, upload_to='files/providers')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='files/providers')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.provider'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('app_name', models.CharField(blank=True, max_length=120, null=True)),
                ('object_type', models.CharField(blank=True, max_length=120, null=True)),
                ('object_id', models.CharField(blank=True, max_length=120, null=True)),
                ('object_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('log', 'Log'), ('error', 'Error'), ('direct', 'Direct'), ('upload', 'Upload'), ('mail', 'Mail'), ('call', 'Call'), ('event', 'Event'), ('state-change', 'State change')], default='log', help_text='Notification type', max_length=15)),
                ('dest_user_id', models.CharField(blank=True, max_length=120, null=True)),
                ('tags', models.CharField(blank=True, max_length=120, null=True)),
                ('id_file', models.CharField(blank=True, max_length=120, null=True)),
                ('file_resource', models.JSONField(blank=True, help_text='File resource related', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
