# Generated by Django 4.0.7 on 2022-09-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='productunit',
            name='action',
            field=models.CharField(blank=True, choices=[('buy', 'Increase by buy'), ('sell', 'Decrease by sell'), ('move', 'Move'), ('fix', 'Fix')], default='fix', help_text='Action type', max_length=20),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
