# Generated by Django 4.0.7 on 2022-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productmove_product_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticUnitCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=20)),
                ('entity_id', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('rfid_code', models.CharField(blank=True, max_length=240, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='files/codes')),
                ('entity_url', models.CharField(blank=True, max_length=240, null=True)),
                ('entity_api_url', models.CharField(blank=True, max_length=240, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rfid_code',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='rfid_code',
        ),
    ]
