# Generated by Django 4.0.7 on 2022-10-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_logisticunitcode_remove_product_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackaging',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
