# Generated by Django 4.0.7 on 2022-09-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productunit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
