# Generated by Django 4.0.7 on 2022-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productpackaging_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmovetype',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
