# Generated by Django 4.0.7 on 2022-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmovetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmove',
            name='add_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmove',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
