# Generated by Django 4.0.7 on 2022-09-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_notification_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='location',
        ),
        migrations.AddField(
            model_name='productunit',
            name='wh_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.whlocation'),
        ),
    ]
