# Generated by Django 4.0.7 on 2022-10-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productmove_add_qr_productmove_rfid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmove',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.client'),
        ),
    ]
