# Generated by Django 4.0.7 on 2022-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_whlocation_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='files/codes'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='files/codes'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='code',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
