# Generated by Django 4.0.7 on 2022-10-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productmove_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmove',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
