# Generated by Django 4.0.7 on 2022-10-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productmove_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmove',
            name='product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productunit'),
        ),
    ]
