# Generated by Django 4.0.7 on 2022-09-28 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_code_product_qrcode_productunit_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='move_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='move_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
