# Generated by Django 4.0.7 on 2022-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productunit_move_date_productunit_move_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
