# Generated by Django 4.0.7 on 2022-11-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productmove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmove',
            name='unit_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
